version: "1.0"

services:
  backend:
    build: ./backend
    image: backend
    container_name: backend_container
    ports:
      - 3031:3031
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./backend/python:/var/www/

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend_container
    ports:
      - 8080:80
    volumes:
      - ./frontend/my-app/build:/var/www
      - ./frontend/nginx/:/etc/nginx/conf.d/
    environment:
      TZ: "Asia/Tokyo"
